const items = [
    {
      id: 1,
      name: "GoPro action camera 4K",
      brand:"GoPro",
      price: "$29.95",
      price1: 29.95,
      image: "https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/items/1.webp",
      description: "Model: X-200",
      spane:"New",
      colr:"#f87217",
      type:"camera",
      description2:"Unleash your inner photographer with our high-performance digital camera. Whether you're a novice or a pro, this camera offers exceptional image quality and creative control. Capture life's moments in stunning detail and share your passion for photography with the world.",
      quantity:0,
    },
    {
      id: 2,
      name: "Canon EOS professional",
      brand:"Canon",
      price: "$590.00",
      price1: 590.00,
      image: "https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/items/2.webp",
      description: "Capacity: 128GB",
      spane:"Offer",
      colr:"Red",
      type:"camera",
      description2:"Unleash your inner photographer with our high-performance digital camera. Whether you're a novice or a pro, this camera offers exceptional image quality and creative control. Capture life's moments in stunning detail and share your passion for photography with the world.",
      quantity:0,
    },
    {
      id: 3,
      name: "Samsung Galaxy 5",
      brand:"Samsung",
      price: "$29.95",
      price1: 29.95,
      image: "https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/items/3.webp",
      description: "Sizes: S, M, XL",
      spane:"",
      type:"phone1",
      description2:"Experience the future in your hands with our cutting-edge mobile phone. Featuring powerful performance, stunning visuals, and a versatile camera, this phone is your gateway to endless possibilities. Stay connected, capture memories, and explore the world with our latest technology.",
      quantity:0,
    },
    {
      id: 4,
      name: "Apple iPhone 13 Pro max",
      brand:"Apple",
      price: "$1099.00",
      price1: 1099.00,
      image: "https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/items/4.webp",
      description: "Color: Black, Memory: 128GB",
      spane:"",
      type:"phone1",
      description2:"Experience the future in your hands with our cutting-edge mobile phone. Featuring powerful performance, stunning visuals, and a versatile camera, this phone is your gateway to endless possibilities. Stay connected, capture memories, and explore the world with our latest technology.",
      quantity:0,
    },
    {
      id: 5,
      name: "Citizen Edifice",
      brand:"Citizen",
      price: "$29.95",
      price1: 29.95,
      image: "https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/items/5.webp",
      description: "Model: S-95",
      spane:"",
      type:"watch",
      description2:"Elevate your fashion game with our classic wristwatch. This timeless accessory exudes sophistication and elegance. Crafted with precision and attention to detail, it's more than just a timepiece; it's a statement of your style.",
      quantity:0,
    },
    {
      id: 6,
      name: "Casio G-Shock",
      brand:"Casio",
      price: "$29.95",
      price1: 29.95,
      image: "https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/items/6.webp",
      description: "Model: X-200",
      spane:"",
      type:"watch",
      description2:"Stay punctual and stylish with our sleek digital watch. With a modern design and advanced features like alarms, timers, and water resistance, this watch is perfect for your active lifestyle. Keep track of time with precision and flair.",
      quantity:0,
    },
    {
      id: 7,
      name: "Boat Rockerz 400",
      brand:"Boat",
      price: "$29.95",
      price1: 29.95,
      image: "https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/items/7.webp",
      description: "Model: SZ-2081",
      type:"headphone",
      spane:"",
      description2:"Immerse yourself in crystal-clear audio with our premium headphones. Whether you're on a long commute or relaxing at home, these headphones deliver an exceptional listening experience. Featuring noise-cancellation technology and comfortable design, they're perfect for music enthusiasts and audiophiles alike.",
      quantity:0,
    },
    {
      id: 8,
      name: "American Tourister",
      brand:"American",
      price:"$29.95",
      price1: 29.95,
      image: "https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/items/8.webp",
      description: "Material: Jeans",
      type:"bag",
      spane:"",
      description2:"Elevate your daily adventures with our versatile backpack. Crafted for durability and functionality, this backpack combines style and practicality seamlessly. With ample storage space and ergonomic design, it's your ideal companion for work, travel, or outdoor pursuits.",
      quantity:0,
    },
    {
      id: 9,
      name: "Blue jeans shorts for Men",
      brand:"Levis",
      price: "$17.00",
      price1: 17.00,
      image: "https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/items/9.webp",
      description: "Sizes: S, M, XL",
      type:"jeans",
      spane:"",
      description2:"Discover ultimate comfort and style with our half jeans. Designed for a relaxed fit and made from high-quality denim, these jeans offer the perfect blend of fashion and comfort. Ideal for casual outings and everyday wear, they're a versatile addition to your wardrobe.",
      quantity:0,
    },
    {
      id: 10,
      name: "Slim fit T-shirt for Men",
      brand:"Lee",
      price: "$9.50",
      price1: 9.50,
      image: "https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/items/10.webp",
      description: "Sizes: S, M, XL",
      type:"shirt",
      spane:"",
      description2:"Upgrade your wardrobe with our stylish shirt, designed for both casual and formal occasions. Made from premium quality fabric, this shirt offers comfort and timeless elegance. Elevate your fashion game with this versatile piece.",
      quantity:0,
    },
    {
      id: 11,
      name: "RedTape Comfy",
      brand:"RedTape",
      price: "$29.95",
      price1: 29.95,
      image: "https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/items/11.webp",
      description: "Sizes: S, M, XL",
      type:"jacket",
      spane:"",
      description2:"Elevate your outerwear collection with our classic jacket, a perfect blend of style and functionality. Crafted with premium materials, it provides warmth and durability, making it ideal for any season. Stay fashionable and cozy with this must-have addition to your wardrobe.",
      quantity:0,
    },
    {
      id: 12,
      name: "NIKE Pro",
      brand:"NIKE",
      price: "$29.95",
      price1: 29.95,
      image: "https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/items/12.webp",
      type:"shirt",
      description: "Material: Jeans",
      spane:"",
      description2:"Upgrade your wardrobe with our stylish shirt, designed for both casual and formal occasions. Made from premium quality fabric, this shirt offers comfort and timeless elegance. Elevate your fashion game with this versatile piece.",
      quantity:0,
    },
    {
      id: 13,
      name: "Blazer Suit Dress Jacket for Men, Blue color",
      brand:"Raymonds",
      price: "$120.00",
      price1: 120.00,
      image: "https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/items/13.webp",
      description: "Material: Linen",
      type:"jacket",
      spane:"",
      description2:"Elevate your outerwear collection with our classic jacket, a perfect blend of style and functionality. Crafted with premium materials, it provides warmth and durability, making it ideal for any season. Stay fashionable and cozy with this must-have addition to your wardrobe.",
      quantity:0,
    },
    {
      id: 14,
      name: "Slim sleeve wallet Italian leather",
      brand:"Bata",
      price: "$510.00",
      price1: 510.00,
      image: "https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/items/14.webp",
      type:"wallet",
      description: "Material: Leather",
      spane:"",
      description2:"Elevate your style with our luxurious leather purse, a timeless accessory crafted from premium, supple leather. Its exquisite design and meticulous craftsmanship make it the perfect blend of fashion and functionality. Available in a range of chic colors, this purse is the epitome of sophistication for any occasion.",
      quantity:0,
    },
    
  ];
  
  export default items;
  